# Generated by Django 3.2.3 on 2021-06-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='user_id',
            new_name='user',
        ),
    ]
