# Generated by Django 3.2.3 on 2021-06-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210610_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuses',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
