# Generated by Django 3.2.3 on 2021-06-14 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labels',
            name='task',
        ),
        migrations.AddField(
            model_name='tasks',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.labels'),
            preserve_default=False,
        ),
    ]
