# Generated by Django 3.2.3 on 2021-06-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210615_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='label',
        ),
        migrations.AddField(
            model_name='tasks',
            name='label',
            field=models.ManyToManyField(to='users.Labels'),
        ),
    ]
