name: Python CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -U pip          
          pip install poetry           

      - name: Install package
        run: |
          make install          

      - name: Build package
        run: |
          make build          

      - name: Django init DB
        run: |            
            make migrate

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test